boost_1_57_0_include = /home/4str0n4ut/boost_1_57_0/install-dir/include
boost_1_57_0_lib = /home/4str0n4ut/boost_1_57_0/install-dir/lib

all:
	g++ main.cpp sha1.h sha1.cpp -lboost_system -lboost_filesystem -lboost_property_tree -I$(boost_1_57_0_include) -L$(boost_1_57_0_lib) -std=c++11 -o 4str0n4ut